name: boilerplate
version: 0.1.0
author: Olivier Chafik <ochafik@google.com>
description: A simple Boilerplate mixin that implements hashCode, operator== and toString based on public fields.
homepage: https://github.com/ochafik/boilerplate.dart
documentation: https://github.com/ochafik/boilerplate.dart
dependencies:
  collection: '>=0.9.3+1 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0+1'
